### ISSUE TITLE
[Task]: enable remote gradle cache and build scan for newly added github action workflow

### ISSUE THREAD

**Issue by Abacn** [apache/beam#28378]
### What needs to happen?

The remote gradle cache and build scan was added in #28212. However, some workflows added after this PR did not include those envs (e.g. Java PreCommit). When the workflow are in stable state, we should check all and see if there is any workflow missing these settings. Also, it would be convenient to attach the build scan link to workflow summary (like what we did for the Website Staging link)

In general, it would be nice to have these configured in a single place instead every workflow yaml needs to add these line
```
env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
```
(as in #28212)

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner
