### ISSUE TITLE
[Bug]: Pub/Sub sources incompatible with Python MapToFields

### ISSUE THREAD

**Issue by Polber** [apache/beam#31434]
### What happened?

`ReadFromPubSub` is incompatible with Python `MapToFields` (or at least I cannot see how to resolve the type errors). A minimal example:
```
pipeline:
  transforms:
    - type: ReadFromPubSub
      name: Source
      config:
        topic: projects/${PROJECT}/topics/${TOPIC_NAME}
        format: json
        schema:
          type: object
          properties:
            foo: {type: string}
    - type: MapToFields
      name: Transform
      config:
        language: python
        append: true
        fields:
          bar:
            expression: "'baz'"
            output_type: string
      input: Source
    - type: WriteToBigQuery
      name: Sink
      config:
        table: ${PROJECT}:${DATASET}.${TABLE}
        numStreams: 1
      input: Transform
```

This fails with

```
Failed to decode Schema due to an error decoding Field proto:

name: "foo"
type {
  nullable: true
  logical_type {
    urn: "beam:logical:pythonsdk_any:v1"
  }
}
```

despite the fact that foo's type is provided in the Pub/Sub schema

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [X] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner
