### ISSUE TITLE
[Bug]: Support error handling in PyTransform

### ISSUE THREAD

**Issue by Polber** [apache/beam#32332]
### What happened?

Beam YAML's PyTransform does not allow a caller to specify `error_handling` similar to other turnkey transforms.

One would expect the following to work:
```
- type: PyTransform
  name: Transform
  config:
    constructor: __callable__
    kwargs:
      source: |
        def process(pcoll):
          return pcoll | beam.Map(lambda row: row.line)
    error_handling:
      output: errors
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [X] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner
